global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "memory-metrics-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8081"]